services:
  app:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/app/data
      - ./app/static/img:/app/static/img       # Mount grote afbeeldingen
      - ./app/static/videos:/app/static/videos # Mount video’s
    environment:
      - FLASK_APP=fittrack.py
      - FLASK_ENV=development