services:
  app:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - FLASK_APP=fittrack.py
      - FLASK_ENV=development