"""empty message

Revision ID: 85c2fd1463aa
Revises: a721fe69219f
Create Date: 2025-07-29 12:15:59.431064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c2fd1463aa'
down_revision = 'a721fe69219f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('is_cardio')

    with op.batch_alter_table('exercise_log', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('distance_km')
        batch_op.drop_column('duration_minutes')

    with op.batch_alter_table('exercise_muscle_association', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False,
                                      server_default=sa.text("(datetime('now'))")))
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('reps',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('workout_session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_constraint('fk_set_logs_workout_session_id', type_='foreignkey')

    with op.batch_alter_table('workout_plan_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan_exercise', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('duration')

    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_set_logs_workout_session_id', 'workout_sessions', ['workout_session_id'], ['id'])
        batch_op.alter_column('workout_session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('reps',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('exercise_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('exercise_muscle_association', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('exercise_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('distance_km', sa.FLOAT(), nullable=True))
        batch_op.alter_column('exercise_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cardio', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
