"""empty message

Revision ID: 8ef50b570dfc
Revises: 005e80c438b8
Create Date: 2025-07-28 15:46:34.290329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef50b570dfc'
down_revision = '005e80c438b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_cardio', sa.Boolean(), nullable=False, server_default=sa.text('0'))
        )

        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)

        op.execute(
            """
            UPDATE exercise
            SET is_cardio = 1
            WHERE LOWER(name) LIKE '%cardio%'
               OR LOWER(name) LIKE '%run%'
               OR LOWER(name) LIKE '%bike%'
               OR LOWER(name) LIKE '%walk%'
               OR LOWER(name) LIKE '%treadmill%'
            """
        )

    with op.batch_alter_table('exercise_log', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('exercise_muscle_association', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('distance_km', sa.Float(), nullable=True))
        batch_op.alter_column('exercise_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('workout_session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.create_foreign_key(
            'fk_set_logs_workout_session_id',
            'workout_sessions',
            ['workout_session_id'],
            ['id']
        )
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sub')

    with op.batch_alter_table('workout_plan_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('distance_km', sa.Float(), nullable=True))
        batch_op.alter_column('exercise_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=True))
        batch_op.alter_column('exercise_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('distance_km')
        batch_op.drop_column('duration_minutes')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub', sa.VARCHAR(length=128), nullable=True))

    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint('fk_set_logs_workout_session_id', type_='foreignkey')
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('reps',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('workout_session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('exercise_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('distance_km')
        batch_op.drop_column('duration_minutes')

    with op.batch_alter_table('exercise_muscle_association', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('exercise_log', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('is_cardio')

    # ### end Alembic commands ###
