"""Recreate migration for user profile and statistics

Revision ID: a59fbc9325d8
Revises: 10c26b33787c
Create Date: 2025-10-04 12:41:37.962799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59fbc9325d8'
down_revision = '10c26b33787c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_pattern', sa.String(length=50), nullable=True),
    sa.Column('recurrence_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fitness_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('goals', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('start_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_workouts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('workout_streak', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('achievements_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_workout_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_workout_date')
        batch_op.drop_column('achievements_count')
        batch_op.drop_column('workout_streak')
        batch_op.drop_column('total_workouts')
        batch_op.drop_column('start_weight')
        batch_op.drop_column('goals')
        batch_op.drop_column('fitness_level')
        batch_op.drop_column('height')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_photo')

    op.drop_table('calendar_events')
    # ### end Alembic commands ###
