"""empty message

Revision ID: a721fe69219f
Revises: 8ef50b570dfc
Create Date: 2025-07-28 16:30:12.251470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a721fe69219f'
down_revision = '8ef50b570dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('distance_km', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_log', schema=None) as batch_op:
        batch_op.drop_column('distance_km')
        batch_op.drop_column('duration_minutes')

    # ### end Alembic commands ###
