"""Fix associatietabelnaam

Revision ID: e86465709366
Revises: 005e80c438b8
Create Date: 2025-06-29 12:42:04.833375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86465709366'
down_revision = '005e80c438b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sub')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
